import { useLocation, useNavigate } from "react-router-dom";
import { useEffect, useState } from "react";
import { saveTrip, getWeather } from "../../services/api.js";
import { useAuth } from "../../context/AuthContext.jsx";
import Navbar from "../../components/layout/Navbar";
import Footer from "../../components/layout/Footer";
import MapView from "../../components/MapView";
import ItineraryView from "../../components/ItineraryView";
import "./TripResult.css";

export default function TripResult() {
  const { state } = useLocation();
  const navigate = useNavigate();
  const { user } = useAuth();

  // Load from state or fallback to localStorage
  const [trip, setTrip] = useState(() => {
    if (state?.result) {
      return { tripData: state.tripData, result: state.result };
    }
    const stored = localStorage.getItem("userTrip") || localStorage.getItem("current_trip");
    return stored ? JSON.parse(stored) : null;
  });

  const [weather, setWeather] = useState(null);
  const [destCoords, setDestCoords] = useState(null);

  const destination = trip?.result?.tripSummary?.destination;

  useEffect(() => {
    if (destination) {
      // Load weather
      getWeather(destination)
        .then(setWeather)
        .catch(() => {});

      // Geocode destination for MapView using Nominatim
      fetch(`https://nominatim.openstreetmap.org/search?format=json&q=${encodeURIComponent(destination)}`)
        .then((res) => res.json())
        .then((data) => {
          if (data && data.length > 0) {
            setDestCoords({
              latitude: parseFloat(data[0].lat),
              longitude: parseFloat(data[0].lon),
              name: data[0].display_name
            });
          }
        })
        .catch(() => {});
    }
  }, [destination]);

  if (!trip || !trip.result) {
    return (
      <>
        <Navbar />
        <main className="trip-result">
          <div className="result-empty">
            <h1>No trip generated yet</h1>
            <button onClick={() => navigate("/planner")}>Start Planning</button>
          </div>
        </main>
        <Footer />
      </>
    );
  }

  const handleSave = async () => {
    if (!user) {
      navigate("/login");
      return;
    }

    try {
      const durationDays = trip.result.tripSummary.durationDays || 3;
      const startDate = trip.tripData.startDate || new Date().toISOString().split("T")[0];
      const endDate = trip.tripData.endDate || new Date(Date.now() + durationDays * 24 * 60 * 60 * 1000).toISOString().split("T")[0];

      await saveTrip({
        destination: destination,
        startDate: startDate,
        endDate: endDate,
        tripSummary: trip.result.tripSummary,
        hotelOptions: trip.result.hotelOptions,
        itinerary: trip.result.itinerary,
        tripPreferences: trip.tripData
      });

      alert("Trip saved to your account.");
    } catch (e) {
      alert(e.message);
    }
  };

  const handlePlanAnother = () => {
    // Reset/Clear local storage under userTrip and current_trip
    localStorage.removeItem("userTrip");
    localStorage.removeItem("current_trip");
    navigate("/planner");
  };


  return (
    <>
      <Navbar />
      <main className="trip-result">
        <header>
          <span>✨ Your AI Travel Plan</span>
          <h1>{destination}</h1>
          <p>Here is your personalized itinerary generated by Gemini.</p>
        </header>

        {/* Render modular ItineraryView */}
        <div style={{ marginTop: "24px" }}>
          <ItineraryView tripPlan={trip.result} />
        </div>

        {/* Weather Panel */}
        {weather?.weather?.current && (
          <section className="result-panel weather-panel" style={{ marginTop: "24px" }}>
            <h2>🌦️ Current weather in {weather.destination?.name || destination}</h2>
            <div className="weather-grid">
              <strong>{weather.weather.current.temperature_2m}°C</strong>
              <span>Feels like {weather.weather.current.apparent_temperature}°C</span>
              <span>💧 {weather.weather.current.relative_humidity_2m}% humidity</span>
              <span>💨 {weather.weather.current.wind_speed_10m} km/h wind</span>
            </div>
          </section>
        )}

        {/* Map Panel */}
        {destCoords && (
          <section className="result-panel" style={{ marginTop: "24px" }}>
            <h2>📍 Destination Map</h2>
            <MapView
              latitude={destCoords.latitude}
              longitude={destCoords.longitude}
              name={destCoords.name}
            />
          </section>
        )}

        {/* Actions */}
        <div className="result-actions" style={{ marginTop: "30px" }}>
          <button onClick={handleSave}>💾 Save Trip</button>
          <button className="secondary" onClick={handlePlanAnother}>
            🔄 Plan Another Trip
          </button>
        </div>
      </main>
      <Footer />
    </>
  );
}
